config/routes.rb
Rails.application.routes.draw do
  #顧客
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  #管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: 'admin/sessions'
  }
  
  root to: 'public/homes#top'#top
 
  scope module: :public do
    get 'bookmark' => 'bookmarks#index'#お気に入り一覧
    resources :menus, only: [:new, :index, :show, :edit, :create, :update, :destroy] do #メニュー機能
      get :search, on: :collection#メニュー検索機能
      get :diagnosis, on: :collection
      resources :menu_items, only: [:edit, :create, :update, :destroy]#メニューアイテム関連機能
      resources :comments, only: [:create, :destroy]#コメント機能
      resource :bookmarks, only: [:create, :destroy]#お気に入り機能
    end
    
    
    resources :plans, only: [:show]
    
    resources :hearings, only: [:new, :show, :create]#診断機能
    resource :customers, only: [:update] do #顧客会員情報機能
      get :bookmarks, on: :collection 
    end
    get 'customer/edit'  => 'customers#edit'
    patch 'customers/withdraw' => 'customers#withdraw'#退会処理
    get 'mypage' => 'customers#show'
    get 'customers/quit' => 'customers#quit'#退会確認ページ
    patch 'customer' => 'customers#update'
    
  end
  
  namespace :admin do
    resources :comments, only: [:destroy] #管理者コメント一覧機能
    resources :menus, only: [:show, :edit, :update, :destroy, :index]do#管理者メニュー機能(一覧、詳細、削除、所属するプランを変更）
      get :search, on: :collection#メニュー検索機能
      resources :menu_items, only: [:destroy]#不適切な投稿を削除できるように
      resources :comments, only: [:index, :destroy] #管理者コメント一覧機能
    end
    resources :customers, only: [:index, :show, :edit, :update]#管理者会員情報機能
    
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :menu
  
  validates :comment, presence: true,length: {maximum: 250}
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  
  def destroy
    refroute = Rails.application.routes.recognize_path(request.referrer)
    @menu = Menu.find(refroute[:id])
    @comments = @menu.comments.order(created_at: :desc).page(params[:page_2]).per(8)
    @comment = Comment.find(params[:id])
    @comment.destroy
    
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_comments_page.html.erb
<div class="admin_comments_area">
  <%= render "admin/comments/index", menu: @menu, comments: @comments %>
</div>

<%= paginate comments, :param_name => 'page_2' %>

app/views/admin/comments/_index.html.erb
<h3 class="my-3 page-title">コメント一覧</h3>
<% if @comments.count == 0 %>
  <p class="page-text">現在、このメニューにコメントはありません。</p>
<% else %>
  <table class="table table-hover table-inverse">
    <% comments.each do |comment| %>
    <tr>
      <td class="text-left page-text">
        <%= link_to admin_customer_path(comment.customer) do %>
          <%= comment.customer.last_name + comment.customer.first_name %>
        <% end %>
      </td>
      <td class="text-right page-text">
        <%= comment.comment %><br />
        <%= link_to "削除", admin_menu_comment_path(comment.menu_id,comment.id), method: :delete, remote: true , "data-confirm" => "本当に消しますか？", class: "btn-text" %>
      </td>
    </tr>
    <% end %>
  </table>
<% end %>

app/views/admin/comments/destroy.js.erb
$(".admin_comments_area").html("<%= j(render "admin/comments/index", menu: @menu, comments: @comments) %>")