config/routes.rb
Rails.application.routes.draw do
  #顧客
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  #管理者
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: 'admin/sessions'
  }
  
  root to: 'public/homes#top'#top
 
  scope module: :public do
    get 'bookmark' => 'bookmarks#index'#お気に入り一覧
    resources :menus, only: [:new, :index, :show, :edit, :create, :update, :destroy] do #メニュー機能
      get :search, on: :collection#メニュー検索機能
      get :diagnosis, on: :collection
      resources :menu_items, only: [:edit, :create, :update, :destroy]#メニューアイテム関連機能
      resources :comments, only: [:create, :destroy]#コメント機能
      resource :bookmarks, only: [:create, :destroy]#お気に入り機能
    end
    
    
    resources :plans, only: [:show]
    
    resources :hearings, only: [:new, :show, :create]#診断機能
    resource :customers, only: [:update] do #顧客会員情報機能
      get :bookmarks, on: :collection 
    end
    get 'customer/edit'  => 'customers#edit'
    patch 'customers/withdraw' => 'customers#withdraw'#退会処理
    get 'mypage' => 'customers#show'
    get 'customers/quit' => 'customers#quit'#退会確認ページ
    patch 'customer' => 'customers#update'
    
  end
  
  namespace :admin do
    resources :comments, only: [:destroy] #管理者コメント一覧機能
    resources :menus, only: [:show, :edit, :update, :destroy, :index]do#管理者メニュー機能(一覧、詳細、削除、所属するプランを変更）
      get :search, on: :collection#メニュー検索機能
      resources :menu_items, only: [:destroy]#不適切な投稿を削除できるように
      resources :comments, only: [:index, :destroy] #管理者コメント一覧機能
    end
    resources :customers, only: [:index, :show, :edit, :update]#管理者会員情報機能
    
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <a class="navbar-brand" href="/">
      <%= image_tag'logo.jpg',size:'170x60' %></a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <div class="mx-auto"></div>
      <div class= "d-block">
        <ul class="navbar-nav ml-auto">
          <li>
            <%= link_to admin_customers_path, class: 'nav-link mx-2 btn-text', style: "color:white;" do %>
              <i class="fas fa-users"></i>会員一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_menus_path, class: 'nav-link mx-2 btn-text', style: "color:white;" do %>
              <i class="fas fa-clipboard-list"></i>メニュー一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link mx-2 btn-text', style: "color:white;" do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>
        </ul>
        <div class="form-inline d-block text-right">  
          <%= form_with url: search_admin_menus_path, local: true, method: :get do |form| %>
            <%= form.text_field :name,class: "page-text" %>
            <%= button_tag type: 'submit' do %>
              <i class="fas fa-search"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>
  

app/views/layouts/_customer_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <a class="navbar-brand" href="/">
      <%= image_tag'logo.jpg',size:'170x60' %></a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown" style="width:100%;">
      <div class="mx-auto"></div>
      <div class= "d-block">
        <ul class="navbar-nav">
          <li>
            <%= link_to new_hearing_path, class: 'nav-link mx-2 btn-text', style: "color:white;" do %>
              <i class="fas fa-stethoscope"></i>診断開始
            <% end %>
          </li>
          <li>
            <%= link_to mypage_path, class: 'nav-link mx-2 btn-text', style: "color:white;" do %>
              <i class="fas fa-user"></i>マイページ
            <% end %>
          </li>
          <li>
            <%= link_to menus_path, class: 'nav-link mx-2 btn-text', style: "color:white;" do %>
              <i class="fas fa-clipboard-list"></i>メニュー一覧
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link mx-2 btn-text', style: "color:white;" do %>
              <i class="fas fa-sign-out-alt"></i>ログアウト
            <% end %>
          </li>
        </ul>
        <div class="form-inline d-block text-right">
          
          <%= form_with url: search_menus_path, local: true, method: :get do |form| %>
            <%= form.text_field :name,class: "page-text" %>
            <%= button_tag type: 'submit' do %>
              <i class="fas fa-search"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>
          

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3 class="page-title"><%= pluralize(obj.errors.count, "件のエラー") %> </h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li class="page-text"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_guest_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <a class="navbar-brand" href="/">
      <%= image_tag'logo.jpg',size:'170x60' %></a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown" style="width:100%;">
      <div class="mx-auto"></div>
      <div class= "d-block">
        <ul class="navbar-nav">
          <li>
            <%= link_to new_hearing_path, class: 'nav-link mx-2 btn-text', style: "color:white;" do %>
              <i class="fas fa-stethoscope"></i>診断開始
            <% end %>
          </li>
          <li>
            <%= link_to menus_path, class: 'nav-link mx-2 btn-text', style:"color:white;" do %>
              <i class="fas fa-clipboard-list"></i>メニュー一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path, class: 'nav-link mx-2 btn-text', style: "color:white;" do %>
              <i class="fas fa-user-plus"></i>新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path, class: 'nav-link mx-2 btn-text', style: "color:white;" do %>
              <i class="fas fa-sign-in-alt"></i>ログイン
            <% end %>
          </li>
        </ul>
        <div class="form-inline d-block text-right">
          <%= form_with url: search_menus_path, local: true, method: :get do |f| %>
            <%= f.text_field :name,class: "page-text" %>
            <%= button_tag type: 'submit' do %>
              <i class="fas fa-search"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if notice %>
 <p id=notice class="alert m-0 text-center" ><%= notice %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RELALTH</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
  </head>

  <body>
    <header>
    <% if current_customer == nil && current_admin == nil %>
      <%= render 'layouts/guest_header' %>
    <% elsif current_customer == nil && current_admin.present? %>
      <%= render 'layouts/admin_header' %>
    <% else current_customer == true && current_admin == nill %>
      <%= render 'layouts/customer_header' %>
    <% end %>
    </header>
     
    <main>
      <div class="notice">
        <%= render "layouts/notice" %>
      </div>
      <div class="py-5">
        <%= yield %>
      </div>
      
    </main>
    
    <footer>
      <p class="footer-text">@RELALTH</p>
    </footer>
  </body>
</html>